### ISSUE TITLE
Request: Add Tornado ID's for Echo Gauntlet (Leagues 5)

### ISSUE THREAD

**Issue by jtallen** [LlemonDuck/the-gauntlet#3]
The new tornadoes added for Leagues 5 in the Echo Hunllef fight are not properly marked. The ID for the new tornadoes is: `14142`

MOID link [here](https://chisel.weirdgloop.org/moid/npc_id.html#14142)

**Comment by LlemonDuck** [comment]
done in c56f56fe78e0d89398e9941db2560dd4688712ba
